"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Bell, Bot, ChevronLeft, ChevronRight, ClipboardList, FileKey2, FolderKanban, LayoutDashboard, LogOut, Menu, Search, Settings, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useApp } from "./app-provider";
const nav=[{href:"/dashboard",icon:LayoutDashboard,key:"dashboard" as const},{href:"/cases",icon:FolderKanban,key:"cases" as const},{href:"/requested-documents",icon:ClipboardList,key:"requestedDocuments" as const},{href:"/evidence-audit",icon:ShieldCheck,key:"evidenceAudit" as const},{href:"/copilot",icon:Bot,key:"copilot" as const}];
export function LanguageSelector(){const {locale,setLocale,t}=useApp();return <select aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value as "en"|"hi")} className="border border-line bg-white px-2 py-1.5 text-sm text-slate-700 focus:outline-none"><option value="en">English</option><option value="hi">हिन्दी</option><option value="more" disabled>{t("moreLanguages")}</option></select>}
export function AppShell({children}:{children:React.ReactNode}){const {t,user,logout}=useApp();const path=usePathname();const router=useRouter();const [collapsed,setCollapsed]=useState(false);return <div className="min-h-screen bg-surface"><aside className={`fixed inset-y-0 left-0 z-20 flex flex-col bg-navy transition-all ${collapsed?"w-[72px]":"w-64"}`}><div className="flex h-16 items-center justify-between border-b border-white/10 px-4"><span className={`font-semibold tracking-[0.2em] text-white ${collapsed?"hidden":""}`}>TESSERACT</span><button aria-label="Toggle sidebar" onClick={()=>setCollapsed(!collapsed)} className="text-slate-300 hover:text-white">{collapsed?<ChevronRight size={18}/>:<ChevronLeft size={18}/>}</button></div><nav className="mt-5">{nav.map(({href,icon:Icon,key})=><Link title={collapsed?t(key):undefined} className={`nav-item ${path.startsWith(href)?"active":""}`} href={href} key={href}><Icon size={18}/>{!collapsed&&<span>{t(key)}</span>}</Link>)}</nav><div className="mt-auto border-t border-white/10 py-3"><Link title={collapsed?t("settings"):undefined} className="nav-item" href="/settings"><Settings size={18}/>{!collapsed&&t("settings")}</Link><button title={collapsed?t("logout"):undefined} onClick={()=>{logout();router.push("/")}} className="nav-item w-full"><LogOut size={18}/>{!collapsed&&t("logout")}</button>{!collapsed&&<div className="mx-3 mt-4 border-t border-white/10 pt-3 text-xs text-slate-400"><p>{t("currentInvestigator")}</p><p className="mt-1 font-medium text-slate-200">{user?.name ?? "—"}</p></div>}</div></aside><main className={`min-h-screen transition-all ${collapsed?"ml-[72px]":"ml-64"}`}><header className="flex h-16 items-center justify-between border-b border-line bg-white px-6"><div className="flex items-center gap-3 text-sm text-slate-500"><Menu size={18}/><span>{path.split("/").filter(Boolean).join(" / ") || "Tesseract"}</span></div><div className="hidden items-center gap-2 rounded border border-line px-2 py-1.5 text-sm text-slate-400 md:flex"><Search size={16}/><span>Search case records</span></div><div className="flex items-center gap-4"><Bell aria-label="Notifications" size={18} className="text-slate-500"/><LanguageSelector/><div className="hidden text-right text-xs sm:block"><p className="font-medium text-slate-800">{user?.name}</p><p className="text-slate-500">{user?.investigator_id}</p></div></div></header><div className="p-6 lg:p-8">{children}</div></main></div>}
